---
- name: update
  hosts:
    orchestrator
    nodes
  tasks:
  - name: update apt repo & cache
    apt: update_cache=yes cache_valid_time=3600
  - name: upgrade all apt packages
    apt: upgrade=dist
  - name: Check if a reboot is needed for server
    register: reboot_required_file
    stat: path=/var/run/reboot-required get_md5=no
  - name: Reboot the Debian or Ubuntu server
    reboot:
      msg: "Reboot initiated by Ansible due to kernel updates"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
   when: reboot_required_file.stat.exists
